/*******************************************************************************
 * Copyright (c) 2015 Fraunhofer Institute for Embedded Systems and
 * Communication Technologies ESK
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * This file is part of ERNEST.
 *
 * Contributors:
 * Fraunhofer ESK - initial API and implementation
 *******************************************************************************/
package ernest.timingspecification.provider;

import ernest.timingspecification.util.TimingspecificationAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class TimingspecificationItemProviderAdapterFactory extends TimingspecificationAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public TimingspecificationItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link ernest.timingspecification.TimingModel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TimingModelItemProvider timingModelItemProvider;

	/**
	 * This creates an adapter for a {@link ernest.timingspecification.TimingModel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTimingModelAdapter() {
		if (timingModelItemProvider == null) {
			timingModelItemProvider = new TimingModelItemProvider(this);
		}

		return timingModelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ernest.timingspecification.AgeTimingConstraint} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AgeTimingConstraintItemProvider ageTimingConstraintItemProvider;

	/**
	 * This creates an adapter for a {@link ernest.timingspecification.AgeTimingConstraint}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAgeTimingConstraintAdapter() {
		if (ageTimingConstraintItemProvider == null) {
			ageTimingConstraintItemProvider = new AgeTimingConstraintItemProvider(this);
		}

		return ageTimingConstraintItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ernest.timingspecification.ReactionConstraint} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReactionConstraintItemProvider reactionConstraintItemProvider;

	/**
	 * This creates an adapter for a {@link ernest.timingspecification.ReactionConstraint}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReactionConstraintAdapter() {
		if (reactionConstraintItemProvider == null) {
			reactionConstraintItemProvider = new ReactionConstraintItemProvider(this);
		}

		return reactionConstraintItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ernest.timingspecification.InputSynchronizationConstraint} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InputSynchronizationConstraintItemProvider inputSynchronizationConstraintItemProvider;

	/**
	 * This creates an adapter for a {@link ernest.timingspecification.InputSynchronizationConstraint}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInputSynchronizationConstraintAdapter() {
		if (inputSynchronizationConstraintItemProvider == null) {
			inputSynchronizationConstraintItemProvider = new InputSynchronizationConstraintItemProvider(this);
		}

		return inputSynchronizationConstraintItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ernest.timingspecification.OutputSynchronizationConstraint} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OutputSynchronizationConstraintItemProvider outputSynchronizationConstraintItemProvider;

	/**
	 * This creates an adapter for a {@link ernest.timingspecification.OutputSynchronizationConstraint}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOutputSynchronizationConstraintAdapter() {
		if (outputSynchronizationConstraintItemProvider == null) {
			outputSynchronizationConstraintItemProvider = new OutputSynchronizationConstraintItemProvider(this);
		}

		return outputSynchronizationConstraintItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ernest.timingspecification.PeriodicRepetitionConstraint} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PeriodicRepetitionConstraintItemProvider periodicRepetitionConstraintItemProvider;

	/**
	 * This creates an adapter for a {@link ernest.timingspecification.PeriodicRepetitionConstraint}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPeriodicRepetitionConstraintAdapter() {
		if (periodicRepetitionConstraintItemProvider == null) {
			periodicRepetitionConstraintItemProvider = new PeriodicRepetitionConstraintItemProvider(this);
		}

		return periodicRepetitionConstraintItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ernest.timingspecification.SporadicRepetitionConstraint} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SporadicRepetitionConstraintItemProvider sporadicRepetitionConstraintItemProvider;

	/**
	 * This creates an adapter for a {@link ernest.timingspecification.SporadicRepetitionConstraint}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSporadicRepetitionConstraintAdapter() {
		if (sporadicRepetitionConstraintItemProvider == null) {
			sporadicRepetitionConstraintItemProvider = new SporadicRepetitionConstraintItemProvider(this);
		}

		return sporadicRepetitionConstraintItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link ernest.timingspecification.ConstraintValidation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConstraintValidationItemProvider constraintValidationItemProvider;

	/**
	 * This creates an adapter for a {@link ernest.timingspecification.ConstraintValidation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConstraintValidationAdapter() {
		if (constraintValidationItemProvider == null) {
			constraintValidationItemProvider = new ConstraintValidationItemProvider(this);
		}

		return constraintValidationItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (timingModelItemProvider != null) timingModelItemProvider.dispose();
		if (ageTimingConstraintItemProvider != null) ageTimingConstraintItemProvider.dispose();
		if (reactionConstraintItemProvider != null) reactionConstraintItemProvider.dispose();
		if (inputSynchronizationConstraintItemProvider != null) inputSynchronizationConstraintItemProvider.dispose();
		if (outputSynchronizationConstraintItemProvider != null) outputSynchronizationConstraintItemProvider.dispose();
		if (periodicRepetitionConstraintItemProvider != null) periodicRepetitionConstraintItemProvider.dispose();
		if (sporadicRepetitionConstraintItemProvider != null) sporadicRepetitionConstraintItemProvider.dispose();
		if (constraintValidationItemProvider != null) constraintValidationItemProvider.dispose();
	}

}
